databases:
  - name: gestionale-db
    plan: free
    databaseName: gestionale
    user: gestionale_user

services:
  - type: web
    name: gestionale-case-vacanza
    env: node
    plan: free
    buildCommand: NODE_ENV=development npm ci && npm run build && npx prisma db push
    startCommand: NODE_ENV=production node server/index.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: gestionale-db
          property: connectionString
