databases:
  - name: gestionale-db
    plan: free
    databaseName: gestionale
    user: gestionale_user

services:
  - type: web
    name: gestionale-case-vacanza
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma db push
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: gestionale-db
          property: connectionString
